# Generated by Django 3.2.3 on 2021-08-13 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='Name',
            new_name='UniqueID',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='email',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='fathersName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='joiningDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='monthlyFees',
            field=models.IntegerField(blank=True, default=1500, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='profilePicture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Perferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice1', to=settings.AUTH_USER_MODEL)),
                ('choice2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice2', to=settings.AUTH_USER_MODEL)),
                ('choice3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice3', to=settings.AUTH_USER_MODEL)),
                ('choice4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice4', to=settings.AUTH_USER_MODEL)),
                ('choice5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice5', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
