# Generated by Django 3.2.3 on 2021-08-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20210813_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinformation',
            old_name='User',
            new_name='user',
        ),
    ]
