# Generated by Django 3.2.3 on 2021-08-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_rename_user_studentinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='UniqueID',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='fathersName',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
