# Generated by Django 3.2.7 on 2021-09-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_auto_20210819_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.studentinformation')),
            ],
        ),
    ]
